version: "3"
services:
  react-app:
    image: react-app
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app

  api-server:
    image: api-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - mern-app
    links:
      - mysql:mysql
    depends_on:
      - mongo
      - mysql

  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/mongodb/

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: lab3_mysql
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - mern-app
    volumes:
      - ./server/students.sql:/docker-entrypoint-initdb.d/students.sql

networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
